name: Automated Contract Testing using Postman CLI

on: 
  - push
  - workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "23374062-4f26e5e1-2a13-483c-94b4-71d033057c50" -e "23374062-736e0653-4e6d-42d5-9a68-2e39f52feef9"
          # Lint your API using Postman CLI
          postman api lint 
